name: Build Backend Docker Image

on:
  workflow_dispatch: # Verhindert automatische Builds und erfordert manuelle Auslösung

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # Das Image wird nur gebaut, aber nicht in eine Registry hochgeladen
          tags: bille-cup-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max